package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA



/**
 * Bmpinfostr generated by hbm2java
 */
public class Bmpinfostr  implements java.io.Serializable {


     private int bmpid;
     private String b0;
     private String b1;
     private String b2;
     private String b3;
     private String b4;
     private String b5;
     private String b6;
     private String b7;
     private String b8;
     private String b9;

    public Bmpinfostr() {
    }

	
    public Bmpinfostr(int bmpid) {
        this.bmpid = bmpid;
    }
    public Bmpinfostr(int bmpid, String b0, String b1, String b2, String b3, String b4, String b5, String b6, String b7, String b8, String b9) {
       this.bmpid = bmpid;
       this.b0 = b0;
       this.b1 = b1;
       this.b2 = b2;
       this.b3 = b3;
       this.b4 = b4;
       this.b5 = b5;
       this.b6 = b6;
       this.b7 = b7;
       this.b8 = b8;
       this.b9 = b9;
    }
   
    public int getBmpid() {
        return this.bmpid;
    }
    
    public void setBmpid(int bmpid) {
        this.bmpid = bmpid;
    }
    public String getB0() {
        return this.b0;
    }
    
    public void setB0(String b0) {
        this.b0 = b0;
    }
    public String getB1() {
        return this.b1;
    }
    
    public void setB1(String b1) {
        this.b1 = b1;
    }
    public String getB2() {
        return this.b2;
    }
    
    public void setB2(String b2) {
        this.b2 = b2;
    }
    public String getB3() {
        return this.b3;
    }
    
    public void setB3(String b3) {
        this.b3 = b3;
    }
    public String getB4() {
        return this.b4;
    }
    
    public void setB4(String b4) {
        this.b4 = b4;
    }
    public String getB5() {
        return this.b5;
    }
    
    public void setB5(String b5) {
        this.b5 = b5;
    }
    public String getB6() {
        return this.b6;
    }
    
    public void setB6(String b6) {
        this.b6 = b6;
    }
    public String getB7() {
        return this.b7;
    }
    
    public void setB7(String b7) {
        this.b7 = b7;
    }
    public String getB8() {
        return this.b8;
    }
    
    public void setB8(String b8) {
        this.b8 = b8;
    }
    public String getB9() {
        return this.b9;
    }
    
    public void setB9(String b9) {
        this.b9 = b9;
    }




}


