package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA



/**
 * Bmpinfo generated by hbm2java
 */
public class Bmpinfo  implements java.io.Serializable {


     private BmpinfoId id;
     private int bmpid;

    public Bmpinfo() {
    }

    public Bmpinfo(BmpinfoId id, int bmpid) {
       this.id = id;
       this.bmpid = bmpid;
    }
   
    public BmpinfoId getId() {
        return this.id;
    }
    
    public void setId(BmpinfoId id) {
        this.id = id;
    }
    public int getBmpid() {
        return this.bmpid;
    }
    
    public void setBmpid(int bmpid) {
        this.bmpid = bmpid;
    }




}


