package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;




/**
 * CbmInitialF2 generated by hbm2java
 */
@Entity
public class CbmInitialF2  implements java.io.Serializable {


    @EmbeddedId
     private CbmInitialF2Id id;
     private Double s0;
     private Double s1;
     private Double s2;
     private Double s3;
     private Double s4;
     private Double s5;
     private Double s6;
     private Double s7;
     private Double s8;
     private Double s9;
     private Double s10;
     private Double s11;
     private Double s12;
     private Double s13;
     private Double s14;
     private Double s15;
     private Double s16;
     private Double s17;
     private Double s18;
     private Double s19;
     private Double s20;
     private Double s21;
     private Double s22;
     private Double s23;
     private Double s24;
     private Double s25;
     private Double s26;
     private Double s27;
     private Double s28;
     private Double s29;
     private Double s30;
     private Double s31;
     private Double s32;
     private Double s33;
     private Double s34;
     private Double s35;
     private Double s36;
     private Double s37;
     private Double s38;
     private Double s39;
     private Double s40;
     private Double s41;
     private Double s42;
     private Double s43;
     private Double s44;
     private Double s45;
     private Double s46;
     private Double s47;
     private Double s48;
     private Double s49;
     private Double s50;
     private Double s51;
     private Double s52;
     private Double s53;
     private Double s54;
     private Double s55;
     private Double s56;
     private Double s57;
     private Double s58;
     private Double s59;
     private Double s60;
     private Double s61;
     private Double s62;
     private Double s63;
     private Double s64;
     private Double s65;
     private Double s66;
     private Double s67;
     private Double s68;
     private Double s69;
     private Double s70;
     private Double s71;
     private Double s72;
     private Double s73;
     private Double s74;
     private Double s75;
     private Double s76;
     private Double s77;
     private Double s78;
     private Double s79;
     private Double s80;
     private Double s81;
     private Double s82;
     private Double s83;
     private Double s84;
     private Double s85;
     private Double s86;
     private Double s87;
     private Double s88;
     private Double s89;
     private Double s90;
     private Double s91;
     private Double s92;
     private Double s93;
     private Double s94;
     private Double s95;
     private Double s96;
     private Double s97;
     private Double s98;
     private Double s99;
     private Double s100;
     private Double s101;
     private Double s102;
     private Double s103;
     private Double s104;
     private Double s105;
     private Double s106;
     private Double s107;
     private Double s108;
     private Double s109;
     private Double s110;
     private Double s111;
     private Double s112;
     private Double s113;
     private Double s114;
     private Double s115;
     private Double s116;
     private Double s117;
     private Double s118;
     private Double s119;
     private Double s120;
     private Double s121;
     private Double s122;
     private Double s123;
     private Double s124;
     private Double s125;
     private Double s126;
     private Double s127;
     private Double s128;
     private Double s129;

    public CbmInitialF2() {
    }

	
    public CbmInitialF2(CbmInitialF2Id id) {
        this.id = id;
    }
    public CbmInitialF2(CbmInitialF2Id id, Double s0, Double s1, Double s2, Double s3, Double s4, Double s5, Double s6, Double s7, Double s8, Double s9, Double s10, Double s11, Double s12, Double s13, Double s14, Double s15, Double s16, Double s17, Double s18, Double s19, Double s20, Double s21, Double s22, Double s23, Double s24, Double s25, Double s26, Double s27, Double s28, Double s29, Double s30, Double s31, Double s32, Double s33, Double s34, Double s35, Double s36, Double s37, Double s38, Double s39, Double s40, Double s41, Double s42, Double s43, Double s44, Double s45, Double s46, Double s47, Double s48, Double s49, Double s50, Double s51, Double s52, Double s53, Double s54, Double s55, Double s56, Double s57, Double s58, Double s59, Double s60, Double s61, Double s62, Double s63, Double s64, Double s65, Double s66, Double s67, Double s68, Double s69, Double s70, Double s71, Double s72, Double s73, Double s74, Double s75, Double s76, Double s77, Double s78, Double s79, Double s80, Double s81, Double s82, Double s83, Double s84, Double s85, Double s86, Double s87, Double s88, Double s89, Double s90, Double s91, Double s92, Double s93, Double s94, Double s95, Double s96, Double s97, Double s98, Double s99, Double s100, Double s101, Double s102, Double s103, Double s104, Double s105, Double s106, Double s107, Double s108, Double s109, Double s110, Double s111, Double s112, Double s113, Double s114, Double s115, Double s116, Double s117, Double s118, Double s119, Double s120, Double s121, Double s122, Double s123, Double s124, Double s125, Double s126, Double s127, Double s128, Double s129) {
       this.id = id;
       this.s0 = s0;
       this.s1 = s1;
       this.s2 = s2;
       this.s3 = s3;
       this.s4 = s4;
       this.s5 = s5;
       this.s6 = s6;
       this.s7 = s7;
       this.s8 = s8;
       this.s9 = s9;
       this.s10 = s10;
       this.s11 = s11;
       this.s12 = s12;
       this.s13 = s13;
       this.s14 = s14;
       this.s15 = s15;
       this.s16 = s16;
       this.s17 = s17;
       this.s18 = s18;
       this.s19 = s19;
       this.s20 = s20;
       this.s21 = s21;
       this.s22 = s22;
       this.s23 = s23;
       this.s24 = s24;
       this.s25 = s25;
       this.s26 = s26;
       this.s27 = s27;
       this.s28 = s28;
       this.s29 = s29;
       this.s30 = s30;
       this.s31 = s31;
       this.s32 = s32;
       this.s33 = s33;
       this.s34 = s34;
       this.s35 = s35;
       this.s36 = s36;
       this.s37 = s37;
       this.s38 = s38;
       this.s39 = s39;
       this.s40 = s40;
       this.s41 = s41;
       this.s42 = s42;
       this.s43 = s43;
       this.s44 = s44;
       this.s45 = s45;
       this.s46 = s46;
       this.s47 = s47;
       this.s48 = s48;
       this.s49 = s49;
       this.s50 = s50;
       this.s51 = s51;
       this.s52 = s52;
       this.s53 = s53;
       this.s54 = s54;
       this.s55 = s55;
       this.s56 = s56;
       this.s57 = s57;
       this.s58 = s58;
       this.s59 = s59;
       this.s60 = s60;
       this.s61 = s61;
       this.s62 = s62;
       this.s63 = s63;
       this.s64 = s64;
       this.s65 = s65;
       this.s66 = s66;
       this.s67 = s67;
       this.s68 = s68;
       this.s69 = s69;
       this.s70 = s70;
       this.s71 = s71;
       this.s72 = s72;
       this.s73 = s73;
       this.s74 = s74;
       this.s75 = s75;
       this.s76 = s76;
       this.s77 = s77;
       this.s78 = s78;
       this.s79 = s79;
       this.s80 = s80;
       this.s81 = s81;
       this.s82 = s82;
       this.s83 = s83;
       this.s84 = s84;
       this.s85 = s85;
       this.s86 = s86;
       this.s87 = s87;
       this.s88 = s88;
       this.s89 = s89;
       this.s90 = s90;
       this.s91 = s91;
       this.s92 = s92;
       this.s93 = s93;
       this.s94 = s94;
       this.s95 = s95;
       this.s96 = s96;
       this.s97 = s97;
       this.s98 = s98;
       this.s99 = s99;
       this.s100 = s100;
       this.s101 = s101;
       this.s102 = s102;
       this.s103 = s103;
       this.s104 = s104;
       this.s105 = s105;
       this.s106 = s106;
       this.s107 = s107;
       this.s108 = s108;
       this.s109 = s109;
       this.s110 = s110;
       this.s111 = s111;
       this.s112 = s112;
       this.s113 = s113;
       this.s114 = s114;
       this.s115 = s115;
       this.s116 = s116;
       this.s117 = s117;
       this.s118 = s118;
       this.s119 = s119;
       this.s120 = s120;
       this.s121 = s121;
       this.s122 = s122;
       this.s123 = s123;
       this.s124 = s124;
       this.s125 = s125;
       this.s126 = s126;
       this.s127 = s127;
       this.s128 = s128;
       this.s129 = s129;
    }
   
    public CbmInitialF2Id getId() {
        return this.id;
    }
    
    public void setId(CbmInitialF2Id id) {
        this.id = id;
    }
    public Double getS0() {
        return this.s0;
    }
    
    public void setS0(Double s0) {
        this.s0 = s0;
    }
    public Double getS1() {
        return this.s1;
    }
    
    public void setS1(Double s1) {
        this.s1 = s1;
    }
    public Double getS2() {
        return this.s2;
    }
    
    public void setS2(Double s2) {
        this.s2 = s2;
    }
    public Double getS3() {
        return this.s3;
    }
    
    public void setS3(Double s3) {
        this.s3 = s3;
    }
    public Double getS4() {
        return this.s4;
    }
    
    public void setS4(Double s4) {
        this.s4 = s4;
    }
    public Double getS5() {
        return this.s5;
    }
    
    public void setS5(Double s5) {
        this.s5 = s5;
    }
    public Double getS6() {
        return this.s6;
    }
    
    public void setS6(Double s6) {
        this.s6 = s6;
    }
    public Double getS7() {
        return this.s7;
    }
    
    public void setS7(Double s7) {
        this.s7 = s7;
    }
    public Double getS8() {
        return this.s8;
    }
    
    public void setS8(Double s8) {
        this.s8 = s8;
    }
    public Double getS9() {
        return this.s9;
    }
    
    public void setS9(Double s9) {
        this.s9 = s9;
    }
    public Double getS10() {
        return this.s10;
    }
    
    public void setS10(Double s10) {
        this.s10 = s10;
    }
    public Double getS11() {
        return this.s11;
    }
    
    public void setS11(Double s11) {
        this.s11 = s11;
    }
    public Double getS12() {
        return this.s12;
    }
    
    public void setS12(Double s12) {
        this.s12 = s12;
    }
    public Double getS13() {
        return this.s13;
    }
    
    public void setS13(Double s13) {
        this.s13 = s13;
    }
    public Double getS14() {
        return this.s14;
    }
    
    public void setS14(Double s14) {
        this.s14 = s14;
    }
    public Double getS15() {
        return this.s15;
    }
    
    public void setS15(Double s15) {
        this.s15 = s15;
    }
    public Double getS16() {
        return this.s16;
    }
    
    public void setS16(Double s16) {
        this.s16 = s16;
    }
    public Double getS17() {
        return this.s17;
    }
    
    public void setS17(Double s17) {
        this.s17 = s17;
    }
    public Double getS18() {
        return this.s18;
    }
    
    public void setS18(Double s18) {
        this.s18 = s18;
    }
    public Double getS19() {
        return this.s19;
    }
    
    public void setS19(Double s19) {
        this.s19 = s19;
    }
    public Double getS20() {
        return this.s20;
    }
    
    public void setS20(Double s20) {
        this.s20 = s20;
    }
    public Double getS21() {
        return this.s21;
    }
    
    public void setS21(Double s21) {
        this.s21 = s21;
    }
    public Double getS22() {
        return this.s22;
    }
    
    public void setS22(Double s22) {
        this.s22 = s22;
    }
    public Double getS23() {
        return this.s23;
    }
    
    public void setS23(Double s23) {
        this.s23 = s23;
    }
    public Double getS24() {
        return this.s24;
    }
    
    public void setS24(Double s24) {
        this.s24 = s24;
    }
    public Double getS25() {
        return this.s25;
    }
    
    public void setS25(Double s25) {
        this.s25 = s25;
    }
    public Double getS26() {
        return this.s26;
    }
    
    public void setS26(Double s26) {
        this.s26 = s26;
    }
    public Double getS27() {
        return this.s27;
    }
    
    public void setS27(Double s27) {
        this.s27 = s27;
    }
    public Double getS28() {
        return this.s28;
    }
    
    public void setS28(Double s28) {
        this.s28 = s28;
    }
    public Double getS29() {
        return this.s29;
    }
    
    public void setS29(Double s29) {
        this.s29 = s29;
    }
    public Double getS30() {
        return this.s30;
    }
    
    public void setS30(Double s30) {
        this.s30 = s30;
    }
    public Double getS31() {
        return this.s31;
    }
    
    public void setS31(Double s31) {
        this.s31 = s31;
    }
    public Double getS32() {
        return this.s32;
    }
    
    public void setS32(Double s32) {
        this.s32 = s32;
    }
    public Double getS33() {
        return this.s33;
    }
    
    public void setS33(Double s33) {
        this.s33 = s33;
    }
    public Double getS34() {
        return this.s34;
    }
    
    public void setS34(Double s34) {
        this.s34 = s34;
    }
    public Double getS35() {
        return this.s35;
    }
    
    public void setS35(Double s35) {
        this.s35 = s35;
    }
    public Double getS36() {
        return this.s36;
    }
    
    public void setS36(Double s36) {
        this.s36 = s36;
    }
    public Double getS37() {
        return this.s37;
    }
    
    public void setS37(Double s37) {
        this.s37 = s37;
    }
    public Double getS38() {
        return this.s38;
    }
    
    public void setS38(Double s38) {
        this.s38 = s38;
    }
    public Double getS39() {
        return this.s39;
    }
    
    public void setS39(Double s39) {
        this.s39 = s39;
    }
    public Double getS40() {
        return this.s40;
    }
    
    public void setS40(Double s40) {
        this.s40 = s40;
    }
    public Double getS41() {
        return this.s41;
    }
    
    public void setS41(Double s41) {
        this.s41 = s41;
    }
    public Double getS42() {
        return this.s42;
    }
    
    public void setS42(Double s42) {
        this.s42 = s42;
    }
    public Double getS43() {
        return this.s43;
    }
    
    public void setS43(Double s43) {
        this.s43 = s43;
    }
    public Double getS44() {
        return this.s44;
    }
    
    public void setS44(Double s44) {
        this.s44 = s44;
    }
    public Double getS45() {
        return this.s45;
    }
    
    public void setS45(Double s45) {
        this.s45 = s45;
    }
    public Double getS46() {
        return this.s46;
    }
    
    public void setS46(Double s46) {
        this.s46 = s46;
    }
    public Double getS47() {
        return this.s47;
    }
    
    public void setS47(Double s47) {
        this.s47 = s47;
    }
    public Double getS48() {
        return this.s48;
    }
    
    public void setS48(Double s48) {
        this.s48 = s48;
    }
    public Double getS49() {
        return this.s49;
    }
    
    public void setS49(Double s49) {
        this.s49 = s49;
    }
    public Double getS50() {
        return this.s50;
    }
    
    public void setS50(Double s50) {
        this.s50 = s50;
    }
    public Double getS51() {
        return this.s51;
    }
    
    public void setS51(Double s51) {
        this.s51 = s51;
    }
    public Double getS52() {
        return this.s52;
    }
    
    public void setS52(Double s52) {
        this.s52 = s52;
    }
    public Double getS53() {
        return this.s53;
    }
    
    public void setS53(Double s53) {
        this.s53 = s53;
    }
    public Double getS54() {
        return this.s54;
    }
    
    public void setS54(Double s54) {
        this.s54 = s54;
    }
    public Double getS55() {
        return this.s55;
    }
    
    public void setS55(Double s55) {
        this.s55 = s55;
    }
    public Double getS56() {
        return this.s56;
    }
    
    public void setS56(Double s56) {
        this.s56 = s56;
    }
    public Double getS57() {
        return this.s57;
    }
    
    public void setS57(Double s57) {
        this.s57 = s57;
    }
    public Double getS58() {
        return this.s58;
    }
    
    public void setS58(Double s58) {
        this.s58 = s58;
    }
    public Double getS59() {
        return this.s59;
    }
    
    public void setS59(Double s59) {
        this.s59 = s59;
    }
    public Double getS60() {
        return this.s60;
    }
    
    public void setS60(Double s60) {
        this.s60 = s60;
    }
    public Double getS61() {
        return this.s61;
    }
    
    public void setS61(Double s61) {
        this.s61 = s61;
    }
    public Double getS62() {
        return this.s62;
    }
    
    public void setS62(Double s62) {
        this.s62 = s62;
    }
    public Double getS63() {
        return this.s63;
    }
    
    public void setS63(Double s63) {
        this.s63 = s63;
    }
    public Double getS64() {
        return this.s64;
    }
    
    public void setS64(Double s64) {
        this.s64 = s64;
    }
    public Double getS65() {
        return this.s65;
    }
    
    public void setS65(Double s65) {
        this.s65 = s65;
    }
    public Double getS66() {
        return this.s66;
    }
    
    public void setS66(Double s66) {
        this.s66 = s66;
    }
    public Double getS67() {
        return this.s67;
    }
    
    public void setS67(Double s67) {
        this.s67 = s67;
    }
    public Double getS68() {
        return this.s68;
    }
    
    public void setS68(Double s68) {
        this.s68 = s68;
    }
    public Double getS69() {
        return this.s69;
    }
    
    public void setS69(Double s69) {
        this.s69 = s69;
    }
    public Double getS70() {
        return this.s70;
    }
    
    public void setS70(Double s70) {
        this.s70 = s70;
    }
    public Double getS71() {
        return this.s71;
    }
    
    public void setS71(Double s71) {
        this.s71 = s71;
    }
    public Double getS72() {
        return this.s72;
    }
    
    public void setS72(Double s72) {
        this.s72 = s72;
    }
    public Double getS73() {
        return this.s73;
    }
    
    public void setS73(Double s73) {
        this.s73 = s73;
    }
    public Double getS74() {
        return this.s74;
    }
    
    public void setS74(Double s74) {
        this.s74 = s74;
    }
    public Double getS75() {
        return this.s75;
    }
    
    public void setS75(Double s75) {
        this.s75 = s75;
    }
    public Double getS76() {
        return this.s76;
    }
    
    public void setS76(Double s76) {
        this.s76 = s76;
    }
    public Double getS77() {
        return this.s77;
    }
    
    public void setS77(Double s77) {
        this.s77 = s77;
    }
    public Double getS78() {
        return this.s78;
    }
    
    public void setS78(Double s78) {
        this.s78 = s78;
    }
    public Double getS79() {
        return this.s79;
    }
    
    public void setS79(Double s79) {
        this.s79 = s79;
    }
    public Double getS80() {
        return this.s80;
    }
    
    public void setS80(Double s80) {
        this.s80 = s80;
    }
    public Double getS81() {
        return this.s81;
    }
    
    public void setS81(Double s81) {
        this.s81 = s81;
    }
    public Double getS82() {
        return this.s82;
    }
    
    public void setS82(Double s82) {
        this.s82 = s82;
    }
    public Double getS83() {
        return this.s83;
    }
    
    public void setS83(Double s83) {
        this.s83 = s83;
    }
    public Double getS84() {
        return this.s84;
    }
    
    public void setS84(Double s84) {
        this.s84 = s84;
    }
    public Double getS85() {
        return this.s85;
    }
    
    public void setS85(Double s85) {
        this.s85 = s85;
    }
    public Double getS86() {
        return this.s86;
    }
    
    public void setS86(Double s86) {
        this.s86 = s86;
    }
    public Double getS87() {
        return this.s87;
    }
    
    public void setS87(Double s87) {
        this.s87 = s87;
    }
    public Double getS88() {
        return this.s88;
    }
    
    public void setS88(Double s88) {
        this.s88 = s88;
    }
    public Double getS89() {
        return this.s89;
    }
    
    public void setS89(Double s89) {
        this.s89 = s89;
    }
    public Double getS90() {
        return this.s90;
    }
    
    public void setS90(Double s90) {
        this.s90 = s90;
    }
    public Double getS91() {
        return this.s91;
    }
    
    public void setS91(Double s91) {
        this.s91 = s91;
    }
    public Double getS92() {
        return this.s92;
    }
    
    public void setS92(Double s92) {
        this.s92 = s92;
    }
    public Double getS93() {
        return this.s93;
    }
    
    public void setS93(Double s93) {
        this.s93 = s93;
    }
    public Double getS94() {
        return this.s94;
    }
    
    public void setS94(Double s94) {
        this.s94 = s94;
    }
    public Double getS95() {
        return this.s95;
    }
    
    public void setS95(Double s95) {
        this.s95 = s95;
    }
    public Double getS96() {
        return this.s96;
    }
    
    public void setS96(Double s96) {
        this.s96 = s96;
    }
    public Double getS97() {
        return this.s97;
    }
    
    public void setS97(Double s97) {
        this.s97 = s97;
    }
    public Double getS98() {
        return this.s98;
    }
    
    public void setS98(Double s98) {
        this.s98 = s98;
    }
    public Double getS99() {
        return this.s99;
    }
    
    public void setS99(Double s99) {
        this.s99 = s99;
    }
    public Double getS100() {
        return this.s100;
    }
    
    public void setS100(Double s100) {
        this.s100 = s100;
    }
    public Double getS101() {
        return this.s101;
    }
    
    public void setS101(Double s101) {
        this.s101 = s101;
    }
    public Double getS102() {
        return this.s102;
    }
    
    public void setS102(Double s102) {
        this.s102 = s102;
    }
    public Double getS103() {
        return this.s103;
    }
    
    public void setS103(Double s103) {
        this.s103 = s103;
    }
    public Double getS104() {
        return this.s104;
    }
    
    public void setS104(Double s104) {
        this.s104 = s104;
    }
    public Double getS105() {
        return this.s105;
    }
    
    public void setS105(Double s105) {
        this.s105 = s105;
    }
    public Double getS106() {
        return this.s106;
    }
    
    public void setS106(Double s106) {
        this.s106 = s106;
    }
    public Double getS107() {
        return this.s107;
    }
    
    public void setS107(Double s107) {
        this.s107 = s107;
    }
    public Double getS108() {
        return this.s108;
    }
    
    public void setS108(Double s108) {
        this.s108 = s108;
    }
    public Double getS109() {
        return this.s109;
    }
    
    public void setS109(Double s109) {
        this.s109 = s109;
    }
    public Double getS110() {
        return this.s110;
    }
    
    public void setS110(Double s110) {
        this.s110 = s110;
    }
    public Double getS111() {
        return this.s111;
    }
    
    public void setS111(Double s111) {
        this.s111 = s111;
    }
    public Double getS112() {
        return this.s112;
    }
    
    public void setS112(Double s112) {
        this.s112 = s112;
    }
    public Double getS113() {
        return this.s113;
    }
    
    public void setS113(Double s113) {
        this.s113 = s113;
    }
    public Double getS114() {
        return this.s114;
    }
    
    public void setS114(Double s114) {
        this.s114 = s114;
    }
    public Double getS115() {
        return this.s115;
    }
    
    public void setS115(Double s115) {
        this.s115 = s115;
    }
    public Double getS116() {
        return this.s116;
    }
    
    public void setS116(Double s116) {
        this.s116 = s116;
    }
    public Double getS117() {
        return this.s117;
    }
    
    public void setS117(Double s117) {
        this.s117 = s117;
    }
    public Double getS118() {
        return this.s118;
    }
    
    public void setS118(Double s118) {
        this.s118 = s118;
    }
    public Double getS119() {
        return this.s119;
    }
    
    public void setS119(Double s119) {
        this.s119 = s119;
    }
    public Double getS120() {
        return this.s120;
    }
    
    public void setS120(Double s120) {
        this.s120 = s120;
    }
    public Double getS121() {
        return this.s121;
    }
    
    public void setS121(Double s121) {
        this.s121 = s121;
    }
    public Double getS122() {
        return this.s122;
    }
    
    public void setS122(Double s122) {
        this.s122 = s122;
    }
    public Double getS123() {
        return this.s123;
    }
    
    public void setS123(Double s123) {
        this.s123 = s123;
    }
    public Double getS124() {
        return this.s124;
    }
    
    public void setS124(Double s124) {
        this.s124 = s124;
    }
    public Double getS125() {
        return this.s125;
    }
    
    public void setS125(Double s125) {
        this.s125 = s125;
    }
    public Double getS126() {
        return this.s126;
    }
    
    public void setS126(Double s126) {
        this.s126 = s126;
    }
    public Double getS127() {
        return this.s127;
    }
    
    public void setS127(Double s127) {
        this.s127 = s127;
    }
    public Double getS128() {
        return this.s128;
    }
    
    public void setS128(Double s128) {
        this.s128 = s128;
    }
    public Double getS129() {
        return this.s129;
    }
    
    public void setS129(Double s129) {
        this.s129 = s129;
    }




}


