package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Entity;
import javax.persistence.Id;




/**
 * ComputerclusterInfo generated by hbm2java
 */
@Entity
public class ComputerclusterInfo  implements java.io.Serializable {


    @Id
     private int clusterid;
     private boolean status;
     private Integer nodes;
     private Integer p;
     private Integer PMax;

    public ComputerclusterInfo() {
    }

	
    public ComputerclusterInfo(int clusterid, boolean status) {
        this.clusterid = clusterid;
        this.status = status;
    }
    public ComputerclusterInfo(int clusterid, boolean status, Integer nodes, Integer p, Integer PMax) {
       this.clusterid = clusterid;
       this.status = status;
       this.nodes = nodes;
       this.p = p;
       this.PMax = PMax;
    }
   
    public int getClusterid() {
        return this.clusterid;
    }
    
    public void setClusterid(int clusterid) {
        this.clusterid = clusterid;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Integer getNodes() {
        return this.nodes;
    }
    
    public void setNodes(Integer nodes) {
        this.nodes = nodes;
    }
    public Integer getP() {
        return this.p;
    }
    
    public void setP(Integer p) {
        this.p = p;
    }
    public Integer getPMax() {
        return this.PMax;
    }
    
    public void setPMax(Integer PMax) {
        this.PMax = PMax;
    }




}


