package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA



/**
 * HdmarchiveNondominated generated by hbm2java
 */
public class HdmarchiveNondominated  implements java.io.Serializable {


     private HdmarchiveNondominatedId id;
     private Byte rating;
     private Double confidence;

    public HdmarchiveNondominated() {
    }

	
    public HdmarchiveNondominated(HdmarchiveNondominatedId id) {
        this.id = id;
    }
    public HdmarchiveNondominated(HdmarchiveNondominatedId id, Byte rating, Double confidence) {
       this.id = id;
       this.rating = rating;
       this.confidence = confidence;
    }
   
    public HdmarchiveNondominatedId getId() {
        return this.id;
    }
    
    public void setId(HdmarchiveNondominatedId id) {
        this.id = id;
    }
    public Byte getRating() {
        return this.rating;
    }
    
    public void setRating(Byte rating) {
        this.rating = rating;
    }
    public Double getConfidence() {
        return this.confidence;
    }
    
    public void setConfidence(Double confidence) {
        this.confidence = confidence;
    }




}


