package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA



/**
 * Igami2EventServer generated by hbm2java
 */
public class Igami2EventServer  implements java.io.Serializable {


     private int userid;
     private boolean event;

    public Igami2EventServer() {
    }

    public Igami2EventServer(int userid, boolean event) {
       this.userid = userid;
       this.event = event;
    }
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public boolean isEvent() {
        return this.event;
    }
    
    public void setEvent(boolean event) {
        this.event = event;
    }




}


