package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Entity;
import javax.persistence.Id;




/**
 * Igami2Maintenance generated by hbm2java
 */
@Entity
public class Igami2Maintenance  implements java.io.Serializable {


    @Id
     private int undermaintenance;

    public Igami2Maintenance() {
    }

    public Igami2Maintenance(int undermaintenance) {
       this.undermaintenance = undermaintenance;
    }
   
    public int getUndermaintenance() {
        return this.undermaintenance;
    }
    
    public void setUndermaintenance(int undermaintenance) {
        this.undermaintenance = undermaintenance;
    }




}


