package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA



/**
 * Individualinfo generated by hbm2java
 */
public class Individualinfo  implements java.io.Serializable {


     private IndividualinfoId id;
     private long indvid;
     private String assignments;

    public Individualinfo() {
    }

	
    public Individualinfo(IndividualinfoId id, long indvid) {
        this.id = id;
        this.indvid = indvid;
    }
    public Individualinfo(IndividualinfoId id, long indvid, String assignments) {
       this.id = id;
       this.indvid = indvid;
       this.assignments = assignments;
    }
   
    public IndividualinfoId getId() {
        return this.id;
    }
    
    public void setId(IndividualinfoId id) {
        this.id = id;
    }
    public long getIndvid() {
        return this.indvid;
    }
    
    public void setIndvid(long indvid) {
        this.indvid = indvid;
    }
    public String getAssignments() {
        return this.assignments;
    }
    
    public void setAssignments(String assignments) {
        this.assignments = assignments;
    }




}


