package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA



/**
 * IndividualinfoId generated by hbm2java
 */
public class IndividualinfoId  implements java.io.Serializable {


     private double f0;
     private double f1;
     private double f2;
     private double f3;
     private double f4;
     private double f5;

    public IndividualinfoId() {
    }

    public IndividualinfoId(double f0, double f1, double f2, double f3, double f4, double f5) {
       this.f0 = f0;
       this.f1 = f1;
       this.f2 = f2;
       this.f3 = f3;
       this.f4 = f4;
       this.f5 = f5;
    }
   
    public double getF0() {
        return this.f0;
    }
    
    public void setF0(double f0) {
        this.f0 = f0;
    }
    public double getF1() {
        return this.f1;
    }
    
    public void setF1(double f1) {
        this.f1 = f1;
    }
    public double getF2() {
        return this.f2;
    }
    
    public void setF2(double f2) {
        this.f2 = f2;
    }
    public double getF3() {
        return this.f3;
    }
    
    public void setF3(double f3) {
        this.f3 = f3;
    }
    public double getF4() {
        return this.f4;
    }
    
    public void setF4(double f4) {
        this.f4 = f4;
    }
    public double getF5() {
        return this.f5;
    }
    
    public void setF5(double f5) {
        this.f5 = f5;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IndividualinfoId) ) return false;
		 IndividualinfoId castOther = ( IndividualinfoId ) other; 
         
		 return (this.getF0()==castOther.getF0())
 && (this.getF1()==castOther.getF1())
 && (this.getF2()==castOther.getF2())
 && (this.getF3()==castOther.getF3())
 && (this.getF4()==castOther.getF4())
 && (this.getF5()==castOther.getF5());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getF0();
         result = 37 * result + (int) this.getF1();
         result = 37 * result + (int) this.getF2();
         result = 37 * result + (int) this.getF3();
         result = 37 * result + (int) this.getF4();
         result = 37 * result + (int) this.getF5();
         return result;
   }   


}


