package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Embeddable;




/**
 * KendallstatsUserDataId generated by hbm2java
 */
@Embeddable
public class KendallstatsUserDataId  implements java.io.Serializable {


     private int userid;
     private int searchid;
     private int globalSessionid;
     private int localSessionid;
     private int sessionid;

    public KendallstatsUserDataId() {
    }

    public KendallstatsUserDataId(int userid, int searchid, int globalSessionid, int localSessionid, int sessionid) {
       this.userid = userid;
       this.searchid = searchid;
       this.globalSessionid = globalSessionid;
       this.localSessionid = localSessionid;
       this.sessionid = sessionid;
    }
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public int getSearchid() {
        return this.searchid;
    }
    
    public void setSearchid(int searchid) {
        this.searchid = searchid;
    }
    public int getGlobalSessionid() {
        return this.globalSessionid;
    }
    
    public void setGlobalSessionid(int globalSessionid) {
        this.globalSessionid = globalSessionid;
    }
    public int getLocalSessionid() {
        return this.localSessionid;
    }
    
    public void setLocalSessionid(int localSessionid) {
        this.localSessionid = localSessionid;
    }
    public int getSessionid() {
        return this.sessionid;
    }
    
    public void setSessionid(int sessionid) {
        this.sessionid = sessionid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof KendallstatsUserDataId) ) return false;
		 KendallstatsUserDataId castOther = ( KendallstatsUserDataId ) other; 
         
		 return (this.getUserid()==castOther.getUserid())
 && (this.getSearchid()==castOther.getSearchid())
 && (this.getGlobalSessionid()==castOther.getGlobalSessionid())
 && (this.getLocalSessionid()==castOther.getLocalSessionid())
 && (this.getSessionid()==castOther.getSessionid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserid();
         result = 37 * result + this.getSearchid();
         result = 37 * result + this.getGlobalSessionid();
         result = 37 * result + this.getLocalSessionid();
         result = 37 * result + this.getSessionid();
         return result;
   }   


}


