package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;




/**
 * Kendallstats generated by hbm2java
 */
@Entity
public class Kendallstats  implements java.io.Serializable {


    @EmbeddedId
     private KendallstatsId id;
     private Double s;
     private Double z;
     private byte hdmselected;

    public Kendallstats() {
    }

	
    public Kendallstats(KendallstatsId id, byte hdmselected) {
        this.id = id;
        this.hdmselected = hdmselected;
    }
    public Kendallstats(KendallstatsId id, Double s, Double z, byte hdmselected) {
       this.id = id;
       this.s = s;
       this.z = z;
       this.hdmselected = hdmselected;
    }
   
    public KendallstatsId getId() {
        return this.id;
    }
    
    public void setId(KendallstatsId id) {
        this.id = id;
    }
    public Double getS() {
        return this.s;
    }
    
    public void setS(Double s) {
        this.s = s;
    }
    public Double getZ() {
        return this.z;
    }
    
    public void setZ(Double z) {
        this.z = z;
    }
    public byte getHdmselected() {
        return this.hdmselected;
    }
    
    public void setHdmselected(byte hdmselected) {
        this.hdmselected = hdmselected;
    }




}


