package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA



/**
 * Newuser generated by hbm2java
 */
public class Newuser  implements java.io.Serializable {


     private int userid;
     private String bmp;
     private String objectiveFun;

    public Newuser() {
    }

    public Newuser(int userid, String bmp, String objectiveFun) {
       this.userid = userid;
       this.bmp = bmp;
       this.objectiveFun = objectiveFun;
    }
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public String getBmp() {
        return this.bmp;
    }
    
    public void setBmp(String bmp) {
        this.bmp = bmp;
    }
    public String getObjectiveFun() {
        return this.objectiveFun;
    }
    
    public void setObjectiveFun(String objectiveFun) {
        this.objectiveFun = objectiveFun;
    }




}


