package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Entity;
import javax.persistence.Id;




/**
 * NewuserParamters generated by hbm2java
 */
@Entity
public class NewuserParamters  implements java.io.Serializable {


    @Id
     private int userid;
     private Integer hdmPopulationSize;
     private Integer sdmPopulationSize;
     private Integer hdmGeneration;
     private Integer sdmGeneration;
     private Integer globalSessionSize;
     private Integer optimizationType;
     private Integer learningType;
     private Double gaMutationProbability;
     private Double gaCrossoverProbability;

    public NewuserParamters() {
    }

	
    public NewuserParamters(int userid) {
        this.userid = userid;
    }
    public NewuserParamters(int userid, Integer hdmPopulationSize, Integer sdmPopulationSize, Integer hdmGeneration, Integer sdmGeneration, Integer globalSessionSize, Integer optimizationType, Integer learningType, Double gaMutationProbability, Double gaCrossoverProbability) {
       this.userid = userid;
       this.hdmPopulationSize = hdmPopulationSize;
       this.sdmPopulationSize = sdmPopulationSize;
       this.hdmGeneration = hdmGeneration;
       this.sdmGeneration = sdmGeneration;
       this.globalSessionSize = globalSessionSize;
       this.optimizationType = optimizationType;
       this.learningType = learningType;
       this.gaMutationProbability = gaMutationProbability;
       this.gaCrossoverProbability = gaCrossoverProbability;
    }
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public Integer getHdmPopulationSize() {
        return this.hdmPopulationSize;
    }
    
    public void setHdmPopulationSize(Integer hdmPopulationSize) {
        this.hdmPopulationSize = hdmPopulationSize;
    }
    public Integer getSdmPopulationSize() {
        return this.sdmPopulationSize;
    }
    
    public void setSdmPopulationSize(Integer sdmPopulationSize) {
        this.sdmPopulationSize = sdmPopulationSize;
    }
    public Integer getHdmGeneration() {
        return this.hdmGeneration;
    }
    
    public void setHdmGeneration(Integer hdmGeneration) {
        this.hdmGeneration = hdmGeneration;
    }
    public Integer getSdmGeneration() {
        return this.sdmGeneration;
    }
    
    public void setSdmGeneration(Integer sdmGeneration) {
        this.sdmGeneration = sdmGeneration;
    }
    public Integer getGlobalSessionSize() {
        return this.globalSessionSize;
    }
    
    public void setGlobalSessionSize(Integer globalSessionSize) {
        this.globalSessionSize = globalSessionSize;
    }
    public Integer getOptimizationType() {
        return this.optimizationType;
    }
    
    public void setOptimizationType(Integer optimizationType) {
        this.optimizationType = optimizationType;
    }
    public Integer getLearningType() {
        return this.learningType;
    }
    
    public void setLearningType(Integer learningType) {
        this.learningType = learningType;
    }
    public Double getGaMutationProbability() {
        return this.gaMutationProbability;
    }
    
    public void setGaMutationProbability(Double gaMutationProbability) {
        this.gaMutationProbability = gaMutationProbability;
    }
    public Double getGaCrossoverProbability() {
        return this.gaCrossoverProbability;
    }
    
    public void setGaCrossoverProbability(Double gaCrossoverProbability) {
        this.gaCrossoverProbability = gaCrossoverProbability;
    }




}


