package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA



/**
 * Sdm generated by hbm2java
 */
public class Sdm  implements java.io.Serializable {


     private SdmId id;
     private byte[] nnm;
     private byte[] nnmExt;
     private byte[] nnmCum;
     private byte[] nnmCumExt;
     private byte[] anfis;
     private String lsf;

    public Sdm() {
    }

	
    public Sdm(SdmId id) {
        this.id = id;
    }
    public Sdm(SdmId id, byte[] nnm, byte[] nnmExt, byte[] nnmCum, byte[] nnmCumExt, byte[] anfis, String lsf) {
       this.id = id;
       this.nnm = nnm;
       this.nnmExt = nnmExt;
       this.nnmCum = nnmCum;
       this.nnmCumExt = nnmCumExt;
       this.anfis = anfis;
       this.lsf = lsf;
    }
   
    public SdmId getId() {
        return this.id;
    }
    
    public void setId(SdmId id) {
        this.id = id;
    }
    public byte[] getNnm() {
        return this.nnm;
    }
    
    public void setNnm(byte[] nnm) {
        this.nnm = nnm;
    }
    public byte[] getNnmExt() {
        return this.nnmExt;
    }
    
    public void setNnmExt(byte[] nnmExt) {
        this.nnmExt = nnmExt;
    }
    public byte[] getNnmCum() {
        return this.nnmCum;
    }
    
    public void setNnmCum(byte[] nnmCum) {
        this.nnmCum = nnmCum;
    }
    public byte[] getNnmCumExt() {
        return this.nnmCumExt;
    }
    
    public void setNnmCumExt(byte[] nnmCumExt) {
        this.nnmCumExt = nnmCumExt;
    }
    public byte[] getAnfis() {
        return this.anfis;
    }
    
    public void setAnfis(byte[] anfis) {
        this.anfis = anfis;
    }
    public String getLsf() {
        return this.lsf;
    }
    
    public void setLsf(String lsf) {
        this.lsf = lsf;
    }




}


