package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Embeddable;




/**
 * SdmDataId generated by hbm2java
 */
@Embeddable
public class SdmDataId  implements java.io.Serializable {


     private int userid;
     private int searchid;
     private int sdmGenerationid;
     private int sdmId;

    public SdmDataId() {
    }

    public SdmDataId(int userid, int searchid, int sdmGenerationid, int sdmId) {
       this.userid = userid;
       this.searchid = searchid;
       this.sdmGenerationid = sdmGenerationid;
       this.sdmId = sdmId;
    }
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public int getSearchid() {
        return this.searchid;
    }
    
    public void setSearchid(int searchid) {
        this.searchid = searchid;
    }
    public int getSdmGenerationid() {
        return this.sdmGenerationid;
    }
    
    public void setSdmGenerationid(int sdmGenerationid) {
        this.sdmGenerationid = sdmGenerationid;
    }
    public int getSdmId() {
        return this.sdmId;
    }
    
    public void setSdmId(int sdmId) {
        this.sdmId = sdmId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SdmDataId) ) return false;
		 SdmDataId castOther = ( SdmDataId ) other; 
         
		 return (this.getUserid()==castOther.getUserid())
 && (this.getSearchid()==castOther.getSearchid())
 && (this.getSdmGenerationid()==castOther.getSdmGenerationid())
 && (this.getSdmId()==castOther.getSdmId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserid();
         result = 37 * result + this.getSearchid();
         result = 37 * result + this.getSdmGenerationid();
         result = 37 * result + this.getSdmId();
         return result;
   }   


}


