package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA



/**
 * SdmModellingDataRandomdata generated by hbm2java
 */
public class SdmModellingDataRandomdata  implements java.io.Serializable {


     private SdmModellingDataRandomdataId id;
     private String datavalues;

    public SdmModellingDataRandomdata() {
    }

	
    public SdmModellingDataRandomdata(SdmModellingDataRandomdataId id) {
        this.id = id;
    }
    public SdmModellingDataRandomdata(SdmModellingDataRandomdataId id, String datavalues) {
       this.id = id;
       this.datavalues = datavalues;
    }
   
    public SdmModellingDataRandomdataId getId() {
        return this.id;
    }
    
    public void setId(SdmModellingDataRandomdataId id) {
        this.id = id;
    }
    public String getDatavalues() {
        return this.datavalues;
    }
    
    public void setDatavalues(String datavalues) {
        this.datavalues = datavalues;
    }




}


