package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA



/**
 * SdmModellingDataRandomdatacumnew generated by hbm2java
 */
public class SdmModellingDataRandomdatacumnew  implements java.io.Serializable {


     private SdmModellingDataRandomdatacumnewId id;
     private String datavalues;

    public SdmModellingDataRandomdatacumnew() {
    }

	
    public SdmModellingDataRandomdatacumnew(SdmModellingDataRandomdatacumnewId id) {
        this.id = id;
    }
    public SdmModellingDataRandomdatacumnew(SdmModellingDataRandomdatacumnewId id, String datavalues) {
       this.id = id;
       this.datavalues = datavalues;
    }
   
    public SdmModellingDataRandomdatacumnewId getId() {
        return this.id;
    }
    
    public void setId(SdmModellingDataRandomdatacumnewId id) {
        this.id = id;
    }
    public String getDatavalues() {
        return this.datavalues;
    }
    
    public void setDatavalues(String datavalues) {
        this.datavalues = datavalues;
    }




}


