package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Entity;
import javax.persistence.Id;




/**
 * SessionInfo generated by hbm2java
 */
@Entity
public class SessionInfo  implements java.io.Serializable {


    @Id
     private int userid;
     private int sessionType;
     private String searchid;
     private String currentSession;
     private Byte sdmSession;
     private Byte nowaiting;
     private Byte leaveforday;
     private Byte jump;
     private Boolean stopSearch;

    public SessionInfo() {
    }

	
    public SessionInfo(int userid, int sessionType) {
        this.userid = userid;
        this.sessionType = sessionType;
    }
    public SessionInfo(int userid, int sessionType, String searchid, String currentSession, Byte sdmSession, Byte nowaiting, Byte leaveforday, Byte jump, Boolean stopSearch) {
       this.userid = userid;
       this.sessionType = sessionType;
       this.searchid = searchid;
       this.currentSession = currentSession;
       this.sdmSession = sdmSession;
       this.nowaiting = nowaiting;
       this.leaveforday = leaveforday;
       this.jump = jump;
       this.stopSearch = stopSearch;
    }
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public int getSessionType() {
        return this.sessionType;
    }
    
    public void setSessionType(int sessionType) {
        this.sessionType = sessionType;
    }
    public String getSearchid() {
        return this.searchid;
    }
    
    public void setSearchid(String searchid) {
        this.searchid = searchid;
    }
    public String getCurrentSession() {
        return this.currentSession;
    }
    
    public void setCurrentSession(String currentSession) {
        this.currentSession = currentSession;
    }
    public Byte getSdmSession() {
        return this.sdmSession;
    }
    
    public void setSdmSession(Byte sdmSession) {
        this.sdmSession = sdmSession;
    }
    public Byte getNowaiting() {
        return this.nowaiting;
    }
    
    public void setNowaiting(Byte nowaiting) {
        this.nowaiting = nowaiting;
    }
    public Byte getLeaveforday() {
        return this.leaveforday;
    }
    
    public void setLeaveforday(Byte leaveforday) {
        this.leaveforday = leaveforday;
    }
    public Byte getJump() {
        return this.jump;
    }
    
    public void setJump(Byte jump) {
        this.jump = jump;
    }
    public Boolean getStopSearch() {
        return this.stopSearch;
    }
    
    public void setStopSearch(Boolean stopSearch) {
        this.stopSearch = stopSearch;
    }




}


