package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA



/**
 * SupercomputerOnhold generated by hbm2java
 */
public class SupercomputerOnhold  implements java.io.Serializable {


     private boolean onhold;

    public SupercomputerOnhold() {
    }

    public SupercomputerOnhold(boolean onhold) {
       this.onhold = onhold;
    }
   
    public boolean isOnhold() {
        return this.onhold;
    }
    
    public void setOnhold(boolean onhold) {
        this.onhold = onhold;
    }




}


