package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA



/**
 * Takefeedback generated by hbm2java
 */
public class Takefeedback  implements java.io.Serializable {


     private TakefeedbackId id;
     private Byte rating;
     private Double confidence;
     private String chosenff;
     private String regionsubbasinid;
     private String chosenbmp;
     private String assignments;
     private Double f0;
     private Double f1;
     private Double f2;
     private Double f3;
     private Double f4;
     private Double f5;
     private String s1;
     private String s2;
     private String s3;
     private String s4;
     private String s5;
     private String s6;
     private String s7;
     private String s8;
     private String s9;
     private String s10;
     private String s11;
     private String s12;
     private String s13;
     private String s14;
     private String s15;
     private String s16;
     private String s17;
     private String s18;
     private String s19;
     private String s20;
     private String s21;
     private String s22;
     private String s23;
     private String s24;
     private String s25;
     private String s26;
     private String s27;
     private String s28;
     private String s29;
     private String s30;
     private String s31;
     private String s32;
     private String s33;
     private String s34;
     private String s35;
     private String s36;
     private String s37;
     private String s38;
     private String s39;
     private String s40;
     private String s41;
     private String s42;
     private String s43;
     private String s44;
     private String s45;
     private String s46;
     private String s47;
     private String s48;
     private String s49;
     private String s50;
     private String s51;
     private String s52;
     private String s53;
     private String s54;
     private String s55;
     private String s56;
     private String s57;
     private String s58;
     private String s59;
     private String s60;
     private String s61;
     private String s62;
     private String s63;
     private String s64;
     private String s65;
     private String s66;
     private String s67;
     private String s68;
     private String s69;
     private String s70;
     private String s71;
     private String s72;
     private String s73;
     private String s74;
     private String s75;
     private String s76;
     private String s77;
     private String s78;
     private String s79;
     private String s80;
     private String s81;
     private String s82;
     private String s83;
     private String s84;
     private String s85;
     private String s86;
     private String s87;
     private String s88;
     private String s89;
     private String s90;
     private String s91;
     private String s92;
     private String s93;
     private String s94;
     private String s95;
     private String s96;
     private String s97;
     private String s98;
     private String s99;
     private String s100;
     private String s101;
     private String s102;
     private String s103;
     private String s104;
     private String s105;
     private String s106;
     private String s107;
     private String s108;
     private String s109;
     private String s110;
     private String s111;
     private String s112;
     private String s113;
     private String s114;
     private String s115;
     private String s116;
     private String s117;
     private String s118;
     private String s119;
     private String s120;
     private String s121;
     private String s122;
     private String s123;
     private String s124;
     private String s125;
     private String s126;
     private String s127;
     private String s128;
     private String s129;
     private String s130;

    public Takefeedback() {
    }

	
    public Takefeedback(TakefeedbackId id) {
        this.id = id;
    }
    public Takefeedback(TakefeedbackId id, Byte rating, Double confidence, String chosenff, String regionsubbasinid, String chosenbmp, String assignments, Double f0, Double f1, Double f2, Double f3, Double f4, Double f5, String s1, String s2, String s3, String s4, String s5, String s6, String s7, String s8, String s9, String s10, String s11, String s12, String s13, String s14, String s15, String s16, String s17, String s18, String s19, String s20, String s21, String s22, String s23, String s24, String s25, String s26, String s27, String s28, String s29, String s30, String s31, String s32, String s33, String s34, String s35, String s36, String s37, String s38, String s39, String s40, String s41, String s42, String s43, String s44, String s45, String s46, String s47, String s48, String s49, String s50, String s51, String s52, String s53, String s54, String s55, String s56, String s57, String s58, String s59, String s60, String s61, String s62, String s63, String s64, String s65, String s66, String s67, String s68, String s69, String s70, String s71, String s72, String s73, String s74, String s75, String s76, String s77, String s78, String s79, String s80, String s81, String s82, String s83, String s84, String s85, String s86, String s87, String s88, String s89, String s90, String s91, String s92, String s93, String s94, String s95, String s96, String s97, String s98, String s99, String s100, String s101, String s102, String s103, String s104, String s105, String s106, String s107, String s108, String s109, String s110, String s111, String s112, String s113, String s114, String s115, String s116, String s117, String s118, String s119, String s120, String s121, String s122, String s123, String s124, String s125, String s126, String s127, String s128, String s129, String s130) {
       this.id = id;
       this.rating = rating;
       this.confidence = confidence;
       this.chosenff = chosenff;
       this.regionsubbasinid = regionsubbasinid;
       this.chosenbmp = chosenbmp;
       this.assignments = assignments;
       this.f0 = f0;
       this.f1 = f1;
       this.f2 = f2;
       this.f3 = f3;
       this.f4 = f4;
       this.f5 = f5;
       this.s1 = s1;
       this.s2 = s2;
       this.s3 = s3;
       this.s4 = s4;
       this.s5 = s5;
       this.s6 = s6;
       this.s7 = s7;
       this.s8 = s8;
       this.s9 = s9;
       this.s10 = s10;
       this.s11 = s11;
       this.s12 = s12;
       this.s13 = s13;
       this.s14 = s14;
       this.s15 = s15;
       this.s16 = s16;
       this.s17 = s17;
       this.s18 = s18;
       this.s19 = s19;
       this.s20 = s20;
       this.s21 = s21;
       this.s22 = s22;
       this.s23 = s23;
       this.s24 = s24;
       this.s25 = s25;
       this.s26 = s26;
       this.s27 = s27;
       this.s28 = s28;
       this.s29 = s29;
       this.s30 = s30;
       this.s31 = s31;
       this.s32 = s32;
       this.s33 = s33;
       this.s34 = s34;
       this.s35 = s35;
       this.s36 = s36;
       this.s37 = s37;
       this.s38 = s38;
       this.s39 = s39;
       this.s40 = s40;
       this.s41 = s41;
       this.s42 = s42;
       this.s43 = s43;
       this.s44 = s44;
       this.s45 = s45;
       this.s46 = s46;
       this.s47 = s47;
       this.s48 = s48;
       this.s49 = s49;
       this.s50 = s50;
       this.s51 = s51;
       this.s52 = s52;
       this.s53 = s53;
       this.s54 = s54;
       this.s55 = s55;
       this.s56 = s56;
       this.s57 = s57;
       this.s58 = s58;
       this.s59 = s59;
       this.s60 = s60;
       this.s61 = s61;
       this.s62 = s62;
       this.s63 = s63;
       this.s64 = s64;
       this.s65 = s65;
       this.s66 = s66;
       this.s67 = s67;
       this.s68 = s68;
       this.s69 = s69;
       this.s70 = s70;
       this.s71 = s71;
       this.s72 = s72;
       this.s73 = s73;
       this.s74 = s74;
       this.s75 = s75;
       this.s76 = s76;
       this.s77 = s77;
       this.s78 = s78;
       this.s79 = s79;
       this.s80 = s80;
       this.s81 = s81;
       this.s82 = s82;
       this.s83 = s83;
       this.s84 = s84;
       this.s85 = s85;
       this.s86 = s86;
       this.s87 = s87;
       this.s88 = s88;
       this.s89 = s89;
       this.s90 = s90;
       this.s91 = s91;
       this.s92 = s92;
       this.s93 = s93;
       this.s94 = s94;
       this.s95 = s95;
       this.s96 = s96;
       this.s97 = s97;
       this.s98 = s98;
       this.s99 = s99;
       this.s100 = s100;
       this.s101 = s101;
       this.s102 = s102;
       this.s103 = s103;
       this.s104 = s104;
       this.s105 = s105;
       this.s106 = s106;
       this.s107 = s107;
       this.s108 = s108;
       this.s109 = s109;
       this.s110 = s110;
       this.s111 = s111;
       this.s112 = s112;
       this.s113 = s113;
       this.s114 = s114;
       this.s115 = s115;
       this.s116 = s116;
       this.s117 = s117;
       this.s118 = s118;
       this.s119 = s119;
       this.s120 = s120;
       this.s121 = s121;
       this.s122 = s122;
       this.s123 = s123;
       this.s124 = s124;
       this.s125 = s125;
       this.s126 = s126;
       this.s127 = s127;
       this.s128 = s128;
       this.s129 = s129;
       this.s130 = s130;
    }
   
    public TakefeedbackId getId() {
        return this.id;
    }
    
    public void setId(TakefeedbackId id) {
        this.id = id;
    }
    public Byte getRating() {
        return this.rating;
    }
    
    public void setRating(Byte rating) {
        this.rating = rating;
    }
    public Double getConfidence() {
        return this.confidence;
    }
    
    public void setConfidence(Double confidence) {
        this.confidence = confidence;
    }
    public String getChosenff() {
        return this.chosenff;
    }
    
    public void setChosenff(String chosenff) {
        this.chosenff = chosenff;
    }
    public String getRegionsubbasinid() {
        return this.regionsubbasinid;
    }
    
    public void setRegionsubbasinid(String regionsubbasinid) {
        this.regionsubbasinid = regionsubbasinid;
    }
    public String getChosenbmp() {
        return this.chosenbmp;
    }
    
    public void setChosenbmp(String chosenbmp) {
        this.chosenbmp = chosenbmp;
    }
    public String getAssignments() {
        return this.assignments;
    }
    
    public void setAssignments(String assignments) {
        this.assignments = assignments;
    }
    public Double getF0() {
        return this.f0;
    }
    
    public void setF0(Double f0) {
        this.f0 = f0;
    }
    public Double getF1() {
        return this.f1;
    }
    
    public void setF1(Double f1) {
        this.f1 = f1;
    }
    public Double getF2() {
        return this.f2;
    }
    
    public void setF2(Double f2) {
        this.f2 = f2;
    }
    public Double getF3() {
        return this.f3;
    }
    
    public void setF3(Double f3) {
        this.f3 = f3;
    }
    public Double getF4() {
        return this.f4;
    }
    
    public void setF4(Double f4) {
        this.f4 = f4;
    }
    public Double getF5() {
        return this.f5;
    }
    
    public void setF5(Double f5) {
        this.f5 = f5;
    }
    public String getS1() {
        return this.s1;
    }
    
    public void setS1(String s1) {
        this.s1 = s1;
    }
    public String getS2() {
        return this.s2;
    }
    
    public void setS2(String s2) {
        this.s2 = s2;
    }
    public String getS3() {
        return this.s3;
    }
    
    public void setS3(String s3) {
        this.s3 = s3;
    }
    public String getS4() {
        return this.s4;
    }
    
    public void setS4(String s4) {
        this.s4 = s4;
    }
    public String getS5() {
        return this.s5;
    }
    
    public void setS5(String s5) {
        this.s5 = s5;
    }
    public String getS6() {
        return this.s6;
    }
    
    public void setS6(String s6) {
        this.s6 = s6;
    }
    public String getS7() {
        return this.s7;
    }
    
    public void setS7(String s7) {
        this.s7 = s7;
    }
    public String getS8() {
        return this.s8;
    }
    
    public void setS8(String s8) {
        this.s8 = s8;
    }
    public String getS9() {
        return this.s9;
    }
    
    public void setS9(String s9) {
        this.s9 = s9;
    }
    public String getS10() {
        return this.s10;
    }
    
    public void setS10(String s10) {
        this.s10 = s10;
    }
    public String getS11() {
        return this.s11;
    }
    
    public void setS11(String s11) {
        this.s11 = s11;
    }
    public String getS12() {
        return this.s12;
    }
    
    public void setS12(String s12) {
        this.s12 = s12;
    }
    public String getS13() {
        return this.s13;
    }
    
    public void setS13(String s13) {
        this.s13 = s13;
    }
    public String getS14() {
        return this.s14;
    }
    
    public void setS14(String s14) {
        this.s14 = s14;
    }
    public String getS15() {
        return this.s15;
    }
    
    public void setS15(String s15) {
        this.s15 = s15;
    }
    public String getS16() {
        return this.s16;
    }
    
    public void setS16(String s16) {
        this.s16 = s16;
    }
    public String getS17() {
        return this.s17;
    }
    
    public void setS17(String s17) {
        this.s17 = s17;
    }
    public String getS18() {
        return this.s18;
    }
    
    public void setS18(String s18) {
        this.s18 = s18;
    }
    public String getS19() {
        return this.s19;
    }
    
    public void setS19(String s19) {
        this.s19 = s19;
    }
    public String getS20() {
        return this.s20;
    }
    
    public void setS20(String s20) {
        this.s20 = s20;
    }
    public String getS21() {
        return this.s21;
    }
    
    public void setS21(String s21) {
        this.s21 = s21;
    }
    public String getS22() {
        return this.s22;
    }
    
    public void setS22(String s22) {
        this.s22 = s22;
    }
    public String getS23() {
        return this.s23;
    }
    
    public void setS23(String s23) {
        this.s23 = s23;
    }
    public String getS24() {
        return this.s24;
    }
    
    public void setS24(String s24) {
        this.s24 = s24;
    }
    public String getS25() {
        return this.s25;
    }
    
    public void setS25(String s25) {
        this.s25 = s25;
    }
    public String getS26() {
        return this.s26;
    }
    
    public void setS26(String s26) {
        this.s26 = s26;
    }
    public String getS27() {
        return this.s27;
    }
    
    public void setS27(String s27) {
        this.s27 = s27;
    }
    public String getS28() {
        return this.s28;
    }
    
    public void setS28(String s28) {
        this.s28 = s28;
    }
    public String getS29() {
        return this.s29;
    }
    
    public void setS29(String s29) {
        this.s29 = s29;
    }
    public String getS30() {
        return this.s30;
    }
    
    public void setS30(String s30) {
        this.s30 = s30;
    }
    public String getS31() {
        return this.s31;
    }
    
    public void setS31(String s31) {
        this.s31 = s31;
    }
    public String getS32() {
        return this.s32;
    }
    
    public void setS32(String s32) {
        this.s32 = s32;
    }
    public String getS33() {
        return this.s33;
    }
    
    public void setS33(String s33) {
        this.s33 = s33;
    }
    public String getS34() {
        return this.s34;
    }
    
    public void setS34(String s34) {
        this.s34 = s34;
    }
    public String getS35() {
        return this.s35;
    }
    
    public void setS35(String s35) {
        this.s35 = s35;
    }
    public String getS36() {
        return this.s36;
    }
    
    public void setS36(String s36) {
        this.s36 = s36;
    }
    public String getS37() {
        return this.s37;
    }
    
    public void setS37(String s37) {
        this.s37 = s37;
    }
    public String getS38() {
        return this.s38;
    }
    
    public void setS38(String s38) {
        this.s38 = s38;
    }
    public String getS39() {
        return this.s39;
    }
    
    public void setS39(String s39) {
        this.s39 = s39;
    }
    public String getS40() {
        return this.s40;
    }
    
    public void setS40(String s40) {
        this.s40 = s40;
    }
    public String getS41() {
        return this.s41;
    }
    
    public void setS41(String s41) {
        this.s41 = s41;
    }
    public String getS42() {
        return this.s42;
    }
    
    public void setS42(String s42) {
        this.s42 = s42;
    }
    public String getS43() {
        return this.s43;
    }
    
    public void setS43(String s43) {
        this.s43 = s43;
    }
    public String getS44() {
        return this.s44;
    }
    
    public void setS44(String s44) {
        this.s44 = s44;
    }
    public String getS45() {
        return this.s45;
    }
    
    public void setS45(String s45) {
        this.s45 = s45;
    }
    public String getS46() {
        return this.s46;
    }
    
    public void setS46(String s46) {
        this.s46 = s46;
    }
    public String getS47() {
        return this.s47;
    }
    
    public void setS47(String s47) {
        this.s47 = s47;
    }
    public String getS48() {
        return this.s48;
    }
    
    public void setS48(String s48) {
        this.s48 = s48;
    }
    public String getS49() {
        return this.s49;
    }
    
    public void setS49(String s49) {
        this.s49 = s49;
    }
    public String getS50() {
        return this.s50;
    }
    
    public void setS50(String s50) {
        this.s50 = s50;
    }
    public String getS51() {
        return this.s51;
    }
    
    public void setS51(String s51) {
        this.s51 = s51;
    }
    public String getS52() {
        return this.s52;
    }
    
    public void setS52(String s52) {
        this.s52 = s52;
    }
    public String getS53() {
        return this.s53;
    }
    
    public void setS53(String s53) {
        this.s53 = s53;
    }
    public String getS54() {
        return this.s54;
    }
    
    public void setS54(String s54) {
        this.s54 = s54;
    }
    public String getS55() {
        return this.s55;
    }
    
    public void setS55(String s55) {
        this.s55 = s55;
    }
    public String getS56() {
        return this.s56;
    }
    
    public void setS56(String s56) {
        this.s56 = s56;
    }
    public String getS57() {
        return this.s57;
    }
    
    public void setS57(String s57) {
        this.s57 = s57;
    }
    public String getS58() {
        return this.s58;
    }
    
    public void setS58(String s58) {
        this.s58 = s58;
    }
    public String getS59() {
        return this.s59;
    }
    
    public void setS59(String s59) {
        this.s59 = s59;
    }
    public String getS60() {
        return this.s60;
    }
    
    public void setS60(String s60) {
        this.s60 = s60;
    }
    public String getS61() {
        return this.s61;
    }
    
    public void setS61(String s61) {
        this.s61 = s61;
    }
    public String getS62() {
        return this.s62;
    }
    
    public void setS62(String s62) {
        this.s62 = s62;
    }
    public String getS63() {
        return this.s63;
    }
    
    public void setS63(String s63) {
        this.s63 = s63;
    }
    public String getS64() {
        return this.s64;
    }
    
    public void setS64(String s64) {
        this.s64 = s64;
    }
    public String getS65() {
        return this.s65;
    }
    
    public void setS65(String s65) {
        this.s65 = s65;
    }
    public String getS66() {
        return this.s66;
    }
    
    public void setS66(String s66) {
        this.s66 = s66;
    }
    public String getS67() {
        return this.s67;
    }
    
    public void setS67(String s67) {
        this.s67 = s67;
    }
    public String getS68() {
        return this.s68;
    }
    
    public void setS68(String s68) {
        this.s68 = s68;
    }
    public String getS69() {
        return this.s69;
    }
    
    public void setS69(String s69) {
        this.s69 = s69;
    }
    public String getS70() {
        return this.s70;
    }
    
    public void setS70(String s70) {
        this.s70 = s70;
    }
    public String getS71() {
        return this.s71;
    }
    
    public void setS71(String s71) {
        this.s71 = s71;
    }
    public String getS72() {
        return this.s72;
    }
    
    public void setS72(String s72) {
        this.s72 = s72;
    }
    public String getS73() {
        return this.s73;
    }
    
    public void setS73(String s73) {
        this.s73 = s73;
    }
    public String getS74() {
        return this.s74;
    }
    
    public void setS74(String s74) {
        this.s74 = s74;
    }
    public String getS75() {
        return this.s75;
    }
    
    public void setS75(String s75) {
        this.s75 = s75;
    }
    public String getS76() {
        return this.s76;
    }
    
    public void setS76(String s76) {
        this.s76 = s76;
    }
    public String getS77() {
        return this.s77;
    }
    
    public void setS77(String s77) {
        this.s77 = s77;
    }
    public String getS78() {
        return this.s78;
    }
    
    public void setS78(String s78) {
        this.s78 = s78;
    }
    public String getS79() {
        return this.s79;
    }
    
    public void setS79(String s79) {
        this.s79 = s79;
    }
    public String getS80() {
        return this.s80;
    }
    
    public void setS80(String s80) {
        this.s80 = s80;
    }
    public String getS81() {
        return this.s81;
    }
    
    public void setS81(String s81) {
        this.s81 = s81;
    }
    public String getS82() {
        return this.s82;
    }
    
    public void setS82(String s82) {
        this.s82 = s82;
    }
    public String getS83() {
        return this.s83;
    }
    
    public void setS83(String s83) {
        this.s83 = s83;
    }
    public String getS84() {
        return this.s84;
    }
    
    public void setS84(String s84) {
        this.s84 = s84;
    }
    public String getS85() {
        return this.s85;
    }
    
    public void setS85(String s85) {
        this.s85 = s85;
    }
    public String getS86() {
        return this.s86;
    }
    
    public void setS86(String s86) {
        this.s86 = s86;
    }
    public String getS87() {
        return this.s87;
    }
    
    public void setS87(String s87) {
        this.s87 = s87;
    }
    public String getS88() {
        return this.s88;
    }
    
    public void setS88(String s88) {
        this.s88 = s88;
    }
    public String getS89() {
        return this.s89;
    }
    
    public void setS89(String s89) {
        this.s89 = s89;
    }
    public String getS90() {
        return this.s90;
    }
    
    public void setS90(String s90) {
        this.s90 = s90;
    }
    public String getS91() {
        return this.s91;
    }
    
    public void setS91(String s91) {
        this.s91 = s91;
    }
    public String getS92() {
        return this.s92;
    }
    
    public void setS92(String s92) {
        this.s92 = s92;
    }
    public String getS93() {
        return this.s93;
    }
    
    public void setS93(String s93) {
        this.s93 = s93;
    }
    public String getS94() {
        return this.s94;
    }
    
    public void setS94(String s94) {
        this.s94 = s94;
    }
    public String getS95() {
        return this.s95;
    }
    
    public void setS95(String s95) {
        this.s95 = s95;
    }
    public String getS96() {
        return this.s96;
    }
    
    public void setS96(String s96) {
        this.s96 = s96;
    }
    public String getS97() {
        return this.s97;
    }
    
    public void setS97(String s97) {
        this.s97 = s97;
    }
    public String getS98() {
        return this.s98;
    }
    
    public void setS98(String s98) {
        this.s98 = s98;
    }
    public String getS99() {
        return this.s99;
    }
    
    public void setS99(String s99) {
        this.s99 = s99;
    }
    public String getS100() {
        return this.s100;
    }
    
    public void setS100(String s100) {
        this.s100 = s100;
    }
    public String getS101() {
        return this.s101;
    }
    
    public void setS101(String s101) {
        this.s101 = s101;
    }
    public String getS102() {
        return this.s102;
    }
    
    public void setS102(String s102) {
        this.s102 = s102;
    }
    public String getS103() {
        return this.s103;
    }
    
    public void setS103(String s103) {
        this.s103 = s103;
    }
    public String getS104() {
        return this.s104;
    }
    
    public void setS104(String s104) {
        this.s104 = s104;
    }
    public String getS105() {
        return this.s105;
    }
    
    public void setS105(String s105) {
        this.s105 = s105;
    }
    public String getS106() {
        return this.s106;
    }
    
    public void setS106(String s106) {
        this.s106 = s106;
    }
    public String getS107() {
        return this.s107;
    }
    
    public void setS107(String s107) {
        this.s107 = s107;
    }
    public String getS108() {
        return this.s108;
    }
    
    public void setS108(String s108) {
        this.s108 = s108;
    }
    public String getS109() {
        return this.s109;
    }
    
    public void setS109(String s109) {
        this.s109 = s109;
    }
    public String getS110() {
        return this.s110;
    }
    
    public void setS110(String s110) {
        this.s110 = s110;
    }
    public String getS111() {
        return this.s111;
    }
    
    public void setS111(String s111) {
        this.s111 = s111;
    }
    public String getS112() {
        return this.s112;
    }
    
    public void setS112(String s112) {
        this.s112 = s112;
    }
    public String getS113() {
        return this.s113;
    }
    
    public void setS113(String s113) {
        this.s113 = s113;
    }
    public String getS114() {
        return this.s114;
    }
    
    public void setS114(String s114) {
        this.s114 = s114;
    }
    public String getS115() {
        return this.s115;
    }
    
    public void setS115(String s115) {
        this.s115 = s115;
    }
    public String getS116() {
        return this.s116;
    }
    
    public void setS116(String s116) {
        this.s116 = s116;
    }
    public String getS117() {
        return this.s117;
    }
    
    public void setS117(String s117) {
        this.s117 = s117;
    }
    public String getS118() {
        return this.s118;
    }
    
    public void setS118(String s118) {
        this.s118 = s118;
    }
    public String getS119() {
        return this.s119;
    }
    
    public void setS119(String s119) {
        this.s119 = s119;
    }
    public String getS120() {
        return this.s120;
    }
    
    public void setS120(String s120) {
        this.s120 = s120;
    }
    public String getS121() {
        return this.s121;
    }
    
    public void setS121(String s121) {
        this.s121 = s121;
    }
    public String getS122() {
        return this.s122;
    }
    
    public void setS122(String s122) {
        this.s122 = s122;
    }
    public String getS123() {
        return this.s123;
    }
    
    public void setS123(String s123) {
        this.s123 = s123;
    }
    public String getS124() {
        return this.s124;
    }
    
    public void setS124(String s124) {
        this.s124 = s124;
    }
    public String getS125() {
        return this.s125;
    }
    
    public void setS125(String s125) {
        this.s125 = s125;
    }
    public String getS126() {
        return this.s126;
    }
    
    public void setS126(String s126) {
        this.s126 = s126;
    }
    public String getS127() {
        return this.s127;
    }
    
    public void setS127(String s127) {
        this.s127 = s127;
    }
    public String getS128() {
        return this.s128;
    }
    
    public void setS128(String s128) {
        this.s128 = s128;
    }
    public String getS129() {
        return this.s129;
    }
    
    public void setS129(String s129) {
        this.s129 = s129;
    }
    public String getS130() {
        return this.s130;
    }
    
    public void setS130(String s130) {
        this.s130 = s130;
    }




}


