package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA



/**
 * TakefeedbackId generated by hbm2java
 */
public class TakefeedbackId  implements java.io.Serializable {


     private int userid;
     private long indvid;

    public TakefeedbackId() {
    }

    public TakefeedbackId(int userid, long indvid) {
       this.userid = userid;
       this.indvid = indvid;
    }
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public long getIndvid() {
        return this.indvid;
    }
    
    public void setIndvid(long indvid) {
        this.indvid = indvid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TakefeedbackId) ) return false;
		 TakefeedbackId castOther = ( TakefeedbackId ) other; 
         
		 return (this.getUserid()==castOther.getUserid())
 && (this.getIndvid()==castOther.getIndvid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserid();
         result = 37 * result + (int) this.getIndvid();
         return result;
   }   


}


