package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA



/**
 * UsersFeedbackTimingId generated by hbm2java
 */
public class UsersFeedbackTimingId  implements java.io.Serializable {


     private int userid;
     private int id;

    public UsersFeedbackTimingId() {
    }

    public UsersFeedbackTimingId(int userid, int id) {
       this.userid = userid;
       this.id = id;
    }
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsersFeedbackTimingId) ) return false;
		 UsersFeedbackTimingId castOther = ( UsersFeedbackTimingId ) other; 
         
		 return (this.getUserid()==castOther.getUserid())
 && (this.getId()==castOther.getId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserid();
         result = 37 * result + this.getId();
         return result;
   }   


}


