package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Userstats generated by hbm2java
 */
public class Userstats  implements java.io.Serializable {


     private UserstatsId id;
     private Date searchBegin;
     private Date searchAbort;
     private Date searchFinish;

    public Userstats() {
    }

	
    public Userstats(UserstatsId id) {
        this.id = id;
    }
    public Userstats(UserstatsId id, Date searchBegin, Date searchAbort, Date searchFinish) {
       this.id = id;
       this.searchBegin = searchBegin;
       this.searchAbort = searchAbort;
       this.searchFinish = searchFinish;
    }
   
    public UserstatsId getId() {
        return this.id;
    }
    
    public void setId(UserstatsId id) {
        this.id = id;
    }
    public Date getSearchBegin() {
        return this.searchBegin;
    }
    
    public void setSearchBegin(Date searchBegin) {
        this.searchBegin = searchBegin;
    }
    public Date getSearchAbort() {
        return this.searchAbort;
    }
    
    public void setSearchAbort(Date searchAbort) {
        this.searchAbort = searchAbort;
    }
    public Date getSearchFinish() {
        return this.searchFinish;
    }
    
    public void setSearchFinish(Date searchFinish) {
        this.searchFinish = searchFinish;
    }




}


