package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * UserstatsFeedbackTiming generated by hbm2java
 */
public class UserstatsFeedbackTiming  implements java.io.Serializable {


     private UserstatsFeedbackTimingId id;
     private Integer page;
     private String event;
     private Date eventtime;
     private long indvid;

    public UserstatsFeedbackTiming() {
    }

	
    public UserstatsFeedbackTiming(UserstatsFeedbackTimingId id) {
        this.id = id;
    }
    public UserstatsFeedbackTiming(UserstatsFeedbackTimingId id, Integer page, String event, Date eventtime, long indvid) {
       this.id = id;
       this.page = page;
       this.event = event;
       this.eventtime = eventtime;
       this.indvid = indvid;
    }

    public long getIndvid() {
        return indvid;
    }

    public void setIndvid(long indvid) {
        this.indvid = indvid;
    }
   
    public UserstatsFeedbackTimingId getId() {
        return this.id;
    }
    
    public void setId(UserstatsFeedbackTimingId id) {
        this.id = id;
    }
    public Integer getPage() {
        return this.page;
    }
    
    public void setPage(Integer page) {
        this.page = page;
    }
    public String getEvent() {
        return this.event;
    }
    
    public void setEvent(String event) {
        this.event = event;
    }
    public Date getEventtime() {
        return this.eventtime;
    }
    
    public void setEventtime(Date eventtime) {
        this.eventtime = eventtime;
    }
}


