package igami2.DataBase.hibernateconfig;
// Generated Jul 17, 2013 10:33:09 PM by Hibernate Tools 3.2.1.GA



/**
 * UsersActivity generated by hbm2java
 */
public class UsersActivity  implements java.io.Serializable {


     private int userid;
     private Boolean active;

    public UsersActivity() {
    }

	
    public UsersActivity(int userid) {
        this.userid = userid;
    }
    public UsersActivity(int userid, Boolean active) {
       this.userid = userid;
       this.active = active;
    }
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }




}


